######################################################################
# Automatically generated by qmake (3.0) mar. janv. 6 21:56:25 2015
######################################################################

TEMPLATE = app
TARGET = Optique
INCLUDEPATH += .

# Input
HEADERS += fenetre.h graphic.h lentille.h rayon.h
SOURCES += fenetre.cpp graphic.cpp lentille.cpp main.cpp rayon.cpp

QT+=widgets
